[package]
name = "snow-draw-engine-c"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
snow-draw-engine-core = { path = "../snow-draw-engine-core" }
snow-draw-engine-document = { path = "../snow-draw-engine-document" }
snow-draw-engine = { path = "../snow-draw-engine" }

[lib]
crate-type = ["staticlib", "rlib"]
path = "src/lib.rs"
