include("${CMAKE_CURRENT_LIST_DIR}/../SnowRustTarget.cmake")

function(expect_target expected)
    snow_rust_target(actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Expected ${expected}, got ${actual}")
    endif()
endfunction()

set(APPLE TRUE)
set(CMAKE_OSX_ARCHITECTURES arm64)
expect_target(aarch64-apple-darwin)
set(CMAKE_OSX_ARCHITECTURES x86_64)
expect_target(x86_64-apple-darwin)
set(CMAKE_OSX_ARCHITECTURES "")
set(CMAKE_SYSTEM_PROCESSOR arm64)
expect_target(aarch64-apple-darwin)
set(APPLE FALSE)
set(WIN32 TRUE)
set(MSVC TRUE)
expect_target(x86_64-pc-windows-msvc)
set(MSVC FALSE)
set(CMAKE_CXX_COMPILER_ID GNU)
expect_target(x86_64-pc-windows-gnu)
set(WIN32 FALSE)
expect_target(x86_64-unknown-linux-gnu)
message(STATUS "Rust target selection checks passed")
