set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PROVIDED_FORTRAN ON)
include("${CMAKE_CURRENT_LIST_DIR}/../vcpkg-windows-triplet-environment.cmake")
