[package]
name = "snow-recording-runtime"
version = "0.1.0"
edition = "2024"
license.workspace = true
build = "build.rs"

[dependencies]
snow-recording-effects = { path = "../snow-recording-effects" }
snow-core = { path = "../snow-core" }
snow-pipeline = { path = "../snow-pipeline" }
snow-capture = { path = "../snow-capture" }
snow-cursor = { path = "../snow-cursor" }
snow-audio-recorder = { path = "../snow-audio-recorder" }
snow-recording-model = { path = "../snow-recording-model" }
snow-recording-export = { path = "../snow-recording-export" }
crossbeam-channel.workspace = true
ffmpeg-next.workspace = true
rayon.workspace = true
num_cpus.workspace = true
smallvec.workspace = true
thiserror.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Imaging",
    "Win32_System_Com",
] }

[dev-dependencies]
proptest = "1.11.0"
tempfile.workspace = true
