#include <QCoreApplication>

// Explicit extraction inventory for diagnostics shared across the worker process and UI.
// The worker sends English diagnostic identifiers; the receiving application translates them.
namespace {
[[maybe_unused]] const char* const updateErrorSources[] = {
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid semantic version"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid update file size"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid update checksum"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid update signature encoding"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid release public key"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Update file could not be read or exceeds its size limit"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not read update file"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not save update state"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not persist update state"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not commit update state"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not read update payload"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not hash update payload"),
    QT_TRANSLATE_NOOP("UpdateErrors",
                      "Update payload size or checksum does not match the signed release"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid update file inventory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Unsafe update file inventory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Update payload is too large"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Conflicting update file paths"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Update metadata is too large"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Unsupported update signature schema"),
    QT_TRANSLATE_NOOP("UpdateErrors",
                      "Release signature is invalid or its signing key is not trusted"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Unsupported update release"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The release must contain all five Windows packages"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Unknown update package variant"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Unexpected update package URL"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Update package has no application executable"),
    QT_TRANSLATE_NOOP("UpdateErrors", "No update package matches this installation"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Update paths must not contain symbolic links"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Update paths must not contain reparse points"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid Snow Shot installation root"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create update destination"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not stage an update file"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not clear update staging directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not update the registered application version"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create update archive reader"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not open update archive"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid update archive entry"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Unexpected, duplicate, or unsafe update archive entry"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create update staging directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not extract update archive entry"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Corrupt update archive entry"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not write update archive entry"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Corrupt update archive checksum"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Incomplete update archive"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Unsupported update recovery journal"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not finalize committed update state"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not remove an incomplete update file"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not finalize update recovery"),
    QT_TRANSLATE_NOOP("UpdateErrors",
                      "This copy does not have valid Snow Shot installation metadata"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Refusing to change a file outside the application payload"),
    QT_TRANSLATE_NOOP("UpdateErrors", "An update file would overwrite the selected data directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Another update transaction is running"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create update work directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The update must be newer than the installed release"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Not enough free space to stage and recover this update"),
    QT_TRANSLATE_NOOP("UpdateErrors",
                      "Update installation metadata does not match the signed release"),
    QT_TRANSLATE_NOOP("UpdateErrors", "An update file conflicts with an existing user file"),
    QT_TRANSLATE_NOOP("UpdateErrors", "An update file conflicts with a directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not back up the current application"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not remove obsolete application file"),
    QT_TRANSLATE_NOOP(
        "UpdateErrors",
        "The new application failed its startup check; restoring the previous version"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create uninstall lock directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "An update is still running"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not remove an owned application file"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create release audit directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Release archive installation metadata mismatch"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The packaged application failed its isolated startup probe"),
    QT_TRANSLATE_NOOP("UpdateErrors",
                      "Could not replace an update file; close applications using it"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The update server must use HTTPS"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create update cache"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not download signed update metadata"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The server offered older release metadata"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The server changed an already published release"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Not enough free space to download the update"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not open the update download file"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The partial update download is invalid"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The update package could not be downloaded"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The server returned an invalid download range"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not restart the update download"),
    QT_TRANSLATE_NOOP("UpdateErrors",
                      "The download exceeded its signed size or could not be saved"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The update download was interrupted"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not save the verified update"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create the application update coordinator"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not launch the application update helper"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Missing updater argument"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not contact the update coordinator"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not send updater status"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The update handoff was not acknowledged"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Invalid updater command argument"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Elevation requires a registered Snow Shot installation"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not open the application process"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The update target does not match its application process"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The release is not newer than this installation"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not stage the verified update package"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The application cancelled the update handoff"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The application did not exit; the update was cancelled"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create updater coordinator"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not launch the installed update helper"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Missing updater operation"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create updater coordinator directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not copy updater coordinator"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not launch updater coordinator"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Update permission was declined or could not be obtained"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not create update worker directory"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Could not launch update worker"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Elevation is unavailable on this platform"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Unknown updater operation"),
    QT_TRANSLATE_NOOP("UpdateErrors", "The update helper timed out"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Application coordinator disconnected"),
    QT_TRANSLATE_NOOP("UpdateErrors", "Application cancelled the update handoff"),
};
}
