[package]
name = "snow-stitch-images-c"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
num_cpus.workspace = true
png.workspace = true
rayon.workspace = true
snow-stitch-images = { path = "../snow-stitch-images", default-features = false }
tempfile.workspace = true
