include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/SnowWindowsArchitecture.cmake")

# Bindgen runs inside a host Rust build script, even when Cargo targets ARM64.
# On Windows ARM, the active Rust toolchain may itself run under x64 emulation.
function(snow_windows_rust_host_architecture output)
    if(DEFINED ENV{RUSTC} AND NOT "$ENV{RUSTC}" STREQUAL "")
        set(_rustc "$ENV{RUSTC}")
    else()
        find_program(SNOW_RUSTC_EXECUTABLE NAMES rustc REQUIRED)
        set(_rustc "${SNOW_RUSTC_EXECUTABLE}")
    endif()
    execute_process(COMMAND "${_rustc}" -vV
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _version ERROR_VARIABLE _error)
    if(NOT _result EQUAL 0 OR NOT _version MATCHES "host: ([^\r\n]+)")
        message(FATAL_ERROR "Cannot determine the Rust host for libclang: ${_error}")
    endif()
    set(_host "${CMAKE_MATCH_1}")
    if(_host MATCHES "^x86_64-pc-windows-")
        set(_architecture x64)
    elseif(_host MATCHES "^aarch64-pc-windows-")
        set(_architecture arm64)
    else()
        message(FATAL_ERROR "Unsupported Windows Rust host for libclang: ${_host}")
    endif()
    set(${output} "${_architecture}" PARENT_SCOPE)
endfunction()

function(_snow_libclang_pe_architecture output path)
    file(SIZE "${path}" _size)
    if(_size LESS 64)
        message(FATAL_ERROR "Invalid Windows libclang PE image: ${path}")
    endif()
    file(READ "${path}" _dos OFFSET 0 LIMIT 64 HEX)
    if(NOT _dos MATCHES "^4d5a")
        message(FATAL_ERROR "Invalid Windows libclang PE image: ${path}")
    endif()
    string(SUBSTRING "${_dos}" 120 8 _offset)
    string(REGEX REPLACE "(..)(..)(..)(..)" "\\4\\3\\2\\1" _offset "${_offset}")
    math(EXPR _offset "0x${_offset}")
    math(EXPR _header_end "${_offset} + 6")
    if(_offset LESS 64 OR _header_end GREATER _size)
        message(FATAL_ERROR "Invalid Windows libclang PE image: ${path}")
    endif()
    file(READ "${path}" _header OFFSET ${_offset} LIMIT 6 HEX)
    if(_header STREQUAL "504500006486")
        set(_architecture x64)
    elseif(_header STREQUAL "5045000064aa")
        set(_architecture arm64)
    else()
        message(FATAL_ERROR "Unsupported Windows libclang PE machine: ${path}")
    endif()
    set(${output} "${_architecture}" PARENT_SCOPE)
endfunction()

function(snow_default_rust_libclang_directory output)
    if(DEFINED ENV{LIBCLANG_PATH} AND NOT "$ENV{LIBCLANG_PATH}" STREQUAL "")
        set(_directory "$ENV{LIBCLANG_PATH}")
    elseif(WIN32)
        snow_windows_rust_host_architecture(_host)
        set(_directory "${SNOW_VCPKG_ROOT}/../llvm-${_host}/bin")
        foreach(_candidate IN ITEMS "${_directory}" "${SNOW_VCPKG_ROOT}/../llvm/bin"
            "$ENV{LLVMInstallDir}/bin" "$ENV{VCINSTALLDIR}/Tools/Llvm/ARM64/bin"
            "$ENV{VCINSTALLDIR}/Tools/Llvm/bin" "C:/Program Files/LLVM/bin")
            if(EXISTS "${_candidate}/libclang.dll")
                _snow_libclang_pe_architecture(_machine "${_candidate}/libclang.dll")
                if(_machine STREQUAL _host)
                    set(_directory "${_candidate}")
                    break()
                endif()
            endif()
        endforeach()
    else()
        set(_directory "${SNOW_VCPKG_ROOT}/../llvm/bin")
    endif()
    set(${output} "${_directory}" PARENT_SCOPE)
endfunction()

function(snow_resolve_rust_libclang_directory output)
    if(NOT WIN32)
        set(${output} "" PARENT_SCOPE)
        return()
    endif()
    snow_windows_rust_host_architecture(_host)
    # Validate both cache entries before applying precedence. A stale alias must
    # never replace a host-validated LIBCLANG_PATH during a later subdirectory.
    foreach(_variable IN ITEMS SNOW_LIBCLANG_BIN_DIR SNOW_SHOT_LIBCLANG_DIR)
        if(DEFINED ${_variable} AND NOT "${${_variable}}" STREQUAL "")
            set(_path "${${_variable}}/libclang.dll")
            if(NOT EXISTS "${_path}")
                message(FATAL_ERROR
                    "${_variable} contains no libclang.dll: ${${_variable}}. "
                    "Clear the stale cache entry or set it to the ${_host} Rust host's libclang directory.")
            endif()
            _snow_libclang_pe_architecture(_machine "${_path}")
            if(NOT _machine STREQUAL _host)
                message(FATAL_ERROR
                    "${_variable} has ${_machine} libclang, but the Rust host requires ${_host}. "
                    "Clear the stale cache entry or select a matching libclang.dll; the Cargo target is independent.")
            endif()
        endif()
    endforeach()
    if(DEFINED ENV{LIBCLANG_PATH} AND NOT "$ENV{LIBCLANG_PATH}" STREQUAL "")
        set(_directory "$ENV{LIBCLANG_PATH}")
    elseif(SNOW_SHOT_LIBCLANG_DIR)
        set(_directory "${SNOW_SHOT_LIBCLANG_DIR}")
    elseif(SNOW_LIBCLANG_BIN_DIR)
        set(_directory "${SNOW_LIBCLANG_BIN_DIR}")
    else()
        snow_default_rust_libclang_directory(_directory)
    endif()
    if(NOT EXISTS "${_directory}/libclang.dll")
        message(FATAL_ERROR
            "The ${_host} Rust host requires libclang.dll. Set LIBCLANG_PATH or SNOW_LIBCLANG_BIN_DIR to its directory.")
    endif()
    _snow_libclang_pe_architecture(_machine "${_directory}/libclang.dll")
    if(NOT _machine STREQUAL _host)
        message(FATAL_ERROR "LIBCLANG_PATH has ${_machine} libclang, but the Rust host requires ${_host}.")
    endif()
    set(${output} "${_directory}" PARENT_SCOPE)
endfunction()
