include_guard(GLOBAL)

function(snow_rust_target output)
    if(APPLE)
        set(_arch "${CMAKE_OSX_ARCHITECTURES}")
        if(NOT _arch)
            set(_arch "${CMAKE_SYSTEM_PROCESSOR}")
        endif()
        if(_arch MATCHES "^(arm64|aarch64)$")
            set(_target aarch64-apple-darwin)
        elseif(_arch MATCHES "^(x86_64|AMD64)$")
            set(_target x86_64-apple-darwin)
        else()
            message(FATAL_ERROR
                "Build one macOS architecture at a time: set CMAKE_OSX_ARCHITECTURES to arm64 or x86_64.")
        endif()
    elseif(MSVC)
        set(_target x86_64-pc-windows-msvc)
    elseif(WIN32 AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|MinGW")
        set(_target x86_64-pc-windows-gnu)
    else()
        set(_target x86_64-unknown-linux-gnu)
    endif()
    set(${output} "${_target}" PARENT_SCOPE)
endfunction()
